version: "3"

services:
  mysql:
    image: mysql:5.7
    ports:
      - 33063:3306
    environment:
      MYSQL_DATABASE: "homestead"
      MYSQL_USER: "homestead"
      MYSQL_PASSWORD: "secret"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
